MvcProjeKampi/Controllers/WriterPanelContentController.cs
using BusinessLayer.Abstract;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelContentController : Controller
    {
        private readonly IContentService _contentService;
        private readonly Context _context;


        public WriterPanelContentController(IContentService contentService, Context context)
        {
            _contentService = contentService;
            _context = context;


        }
        public ActionResult MyContent()
        {
            string girisYapankullanini = (string)Session["WriterMail"];
            int girisYapanId = _context.Writers.Where(x => x.WriterMail == girisYapankullanini).Select(x => x.WriterID).FirstOrDefault();

            var values = _context.Contents.Where(x => x.WriterID == girisYapanId).ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.HeadingName = _context.Headings.Where(x => x.HeadingID == id).Select(x => x.HeadingName).FirstOrDefault();
            ViewBag.İd = id;
            return View();
        }


        [HttpPost]
        public ActionResult AddContent(Content content)
        {
            string girisYapankullanini = (string)Session["WriterMail"];
            int girisYapanId = _context.Writers.Where(x => x.WriterMail == girisYapankullanini).Select(x => x.WriterID).FirstOrDefault();

            content.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            content.WriterID = girisYapanId;
            content.ContentStatus = true;

            _contentService.TInsert(content);
            return RedirectToAction("MyContent");
        }

        //profilim sayfası yok
        //tüm başlıklarda page yapıalcak
        //session göre mesajben yaptım 
        //oturum yönetimini mimamiye taşıma
        //token kullanıkı
        //


    }
}

MvcProjeKampi/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>İçerik Ekleme Sayfası</h2>



@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" value="@ViewBag.İd" name="HeadingID" />
        @Html.Label("Başlık:")
    <label> @ViewBag.HeadingName</label>
        <br />
        @Html.Label("İçerik")
        @Html.TextAreaFor(x => x.ContentValue, 10, 30, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ContentValue)
        <br />



        <button class="btn btn-info">İçerik Oluştur</button>

    </div>
}

MvcProjeKampi/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="timeline">
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a> </h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                            }

                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>